#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 30 20:33:48 2020

@author: Sergey
"""

def square(x):
    '''
    x: int or float.
    '''
    # Your code here
    return (x * x)
